kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: auth0-hello-world
  name: auth0-hello-world
spec:
  progressDeadlineSeconds: 1200
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: auth0-hello-world
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: auth0-hello-world
    spec:
      containers:
      - image: callone.azurecr.io/auth0-hello-world:1
        imagePullPolicy: IfNotPresent
        name: auth0-hello-world
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: auth0-hello-world-proxy
  name: auth0-hello-world-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: auth0-hello-world-proxy
  template:
    metadata:
      labels:
        k8s-app: auth0-hello-world-proxy
    spec:
      containers:
      - args:
        - --cookie-expire=24h0m0s
        - --cookie-refresh=0h60m0s
        - --email-domain=*
        - --http-address=0.0.0.0:4180
        - --provider=oidc
        - --set-authorization-header=true
        - --skip-provider-button=true
        - --oidc-issuer-url=https://login-dev.callone.com/
        - --login-url=https://login-dev.callone.com/authorize
        - --redeem-url=https://login-dev.callone.com/oauth/token
        - --validate-url=https://login-dev.callone.com/userinfo
        - --upstream=file:///dev/null
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: auth0-hello-world-proxy-secret
              key: client-id
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth0-hello-world-proxy-secret
              key: client-secret
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: auth0-hello-world-proxy-secret
              key: cookie-secret
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        imagePullPolicy: Always
        name: auth0-hello-world-proxy
        ports:
        - containerPort: 4180
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: auth0-hello-world-proxy
  name: auth0-hello-world-proxy
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    k8s-app: auth0-hello-world-proxy